# Generated by Django 3.1 on 2020-08-21 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200822_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='emp_sal',
            new_name='emp_salary',
        ),
    ]
